# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object_detection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='object_detection.proto',
  package='object_detection',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16object_detection.proto\x12\x10object_detection\"J\n\nArrayImage\x12\x13\n\x0bImage_bytes\x18\x01 \x01(\x0c\x12\x13\n\x0bImage_shape\x18\x02 \x03(\x05\x12\x12\n\nImage_type\x18\x03 \x01(\t\"n\n\x12ObjectDetectResult\x12\x13\n\x0bobjects_bbs\x18\x01 \x01(\x0c\x12\x19\n\x11objects_bbs_shape\x18\x02 \x03(\x05\x12\x18\n\x10objects_bbs_type\x18\x03 \x01(\t\x12\x0e\n\x06labels\x18\x04 \x03(\t2\x82\x01\n ObjectDetectionProcessingService\x12^\n\x16ObjectDetectionProcess\x12\x1c.object_detection.ArrayImage\x1a$.object_detection.ObjectDetectResult\"\x00\x62\x06proto3')
)




_ARRAYIMAGE = _descriptor.Descriptor(
  name='ArrayImage',
  full_name='object_detection.ArrayImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Image_bytes', full_name='object_detection.ArrayImage.Image_bytes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Image_shape', full_name='object_detection.ArrayImage.Image_shape', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Image_type', full_name='object_detection.ArrayImage.Image_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=118,
)


_OBJECTDETECTRESULT = _descriptor.Descriptor(
  name='ObjectDetectResult',
  full_name='object_detection.ObjectDetectResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='objects_bbs', full_name='object_detection.ObjectDetectResult.objects_bbs', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='objects_bbs_shape', full_name='object_detection.ObjectDetectResult.objects_bbs_shape', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='objects_bbs_type', full_name='object_detection.ObjectDetectResult.objects_bbs_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='labels', full_name='object_detection.ObjectDetectResult.labels', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=230,
)

DESCRIPTOR.message_types_by_name['ArrayImage'] = _ARRAYIMAGE
DESCRIPTOR.message_types_by_name['ObjectDetectResult'] = _OBJECTDETECTRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ArrayImage = _reflection.GeneratedProtocolMessageType('ArrayImage', (_message.Message,), {
  'DESCRIPTOR' : _ARRAYIMAGE,
  '__module__' : 'object_detection_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.ArrayImage)
  })
_sym_db.RegisterMessage(ArrayImage)

ObjectDetectResult = _reflection.GeneratedProtocolMessageType('ObjectDetectResult', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTDETECTRESULT,
  '__module__' : 'object_detection_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.ObjectDetectResult)
  })
_sym_db.RegisterMessage(ObjectDetectResult)



_OBJECTDETECTIONPROCESSINGSERVICE = _descriptor.ServiceDescriptor(
  name='ObjectDetectionProcessingService',
  full_name='object_detection.ObjectDetectionProcessingService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=233,
  serialized_end=363,
  methods=[
  _descriptor.MethodDescriptor(
    name='ObjectDetectionProcess',
    full_name='object_detection.ObjectDetectionProcessingService.ObjectDetectionProcess',
    index=0,
    containing_service=None,
    input_type=_ARRAYIMAGE,
    output_type=_OBJECTDETECTRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_OBJECTDETECTIONPROCESSINGSERVICE)

DESCRIPTOR.services_by_name['ObjectDetectionProcessingService'] = _OBJECTDETECTIONPROCESSINGSERVICE

# @@protoc_insertion_point(module_scope)
